name: Build and push

on:
  push:
    branches:
      - master

jobs:

  build-and-publish:
    name: Build image for production
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACTIONS_SECRET  }}

      - name: Build and push ui
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            NODE_ENV=prod
          file: Dockerfile
          push: true
          tags: ghcr.io/m0rgan01/React-sand-box:main

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
